using System;
using System.Collections.Generic;
using System.Text;
using Dhgms.Nucleotide.Model;

namespace Dhgms.Nucleotide.Models
{
    /// <summary>
    /// Generation Model for Service Boundaries
    /// </summary>
    public interface IServiceGenerationModel
    {
        IEntityGenerationModel EntityGenerationModel { get; }

        /// <summary>
        /// Whether to generate only the list and get methods on a service.
        /// Useful for services that represent entities that can only be
        /// generated by an internal process.
        /// </summary>
        bool ReadOnly { get; }
    }
}
